### ISSUE TITLE
Services are not started - environment/user problem

### ISSUE THREAD

**Issue by remyroy** [ethstaker-core/stakehouse#6]
There seems to be an environment/user issue with stakehouse where rocketpool is installed in the user ~/bin directory but config.yml is created in /root preventing the services from starting.

The logs I was getting are:

```
Could not read Rocket Pool config at ~/.rocketpool/config.yml: exit status 1

Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/rocketpool_eth1/json: dial unix /var/run/docker.sock: connect: permission denied
```

Config was in /root/.rocketpool/config.yml but the rocketpool cli was in /home/remyroy/bin/rocketpool .

**Comment by remyroy** [comment]
![Screenshot_from_2021-03-16_07-12-27](https://user-images.githubusercontent.com/303593/111332656-5b274680-8648-11eb-957c-a39ac93c30eb.png)

**Comment by remyroy** [comment]
This was on a clean install of ubuntu-20.04.2.0-desktop-amd64

**Comment by grasponcrypto** [comment]
So the issue is that when you install docker, it creates a new docker group to which the $USER is added.  The docker group will not be part of the user's active session until logging out and back in.  Somehow a new shell session will need to be started for the docker commands.

**Comment by grasponcrypto** [comment]
I believe one option might be to add an if statement before docker calls.  something like:
````
if (groups("docker")) {
  do what we currently do;
  } else {
  "echo" + password + " | su - $USER"
  }
  ````

**Comment by remyroy** [comment]
I'm somewhat confused by this issue. I'm not sure the rocketpool tool should be installed with the root user (using the `--allow-root` flag) on https://github.com/ethstaker-core/stakehouse/blob/main/src/react/commands/RocketPool.ts#L53 .

Trying to run rocketpool as root or with sudo even give us this message:

```
rocketpool should not be run as root. Please try again without 'sudo'.
If you want to run rocketpool as root anyway, use the '--allow-root' option to override this warning.
```

**Comment by colfax23** [comment]
Ah.  I had originally done that to get around having to input the password after being prompted during the install - installing docker requires root: https://github.com/rocket-pool/smartnode-install/blob/master/install.sh#L126

It was a hack to not have to deal with an additional prompt.

Looking back on it now, that could probably be refactored to give the password as an additional prompt (the first, I believe).  That may solve this issue entirely.

I can give that a try tomorrow (I'll be afk most of the day today), or if you have time feel free to try it out today.
